config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'cocktails/ingredients/new', to: 'ingredients#new'
  get 'cocktails/ingredients', to: 'ingredients#index'
  get '/ingredients', to: 'ingredients#index'
  post '/ingredients', to: 'ingredients#create'
  patch 'cocktails/:id', to: 'cocktails#create'
  resources :cocktails, only: [:index, :show, :new, :create] do
    resources :doses, only: [:new, :create]
  end
  post '/new_ingredient', to: 'cocktails#new_ingredient'
  resources :doses, only: [:destroy]
  # resources :ingredients, only: [:index, :show, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  mount_uploader :photo, PhotoUploader
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  has_many :reviews
  validates :name, uniqueness: true, presence: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient, dependent: :destroy

  validates :description, presence: true
  # validates :cocktail_id, presence: true
  # validates :ingredient_id, presence: true
  validates :cocktail, uniqueness: { scope: :ingredient }, presence: true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  has_many :cocktails, through: :doses
  validates :name, presence: true, uniqueness: true
  before_destroy :check_doses

  def check_doses
    raise ActiveRecord::InvalidForeignKey unless self.doses.empty?
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :cocktail
  validates :rating, inclusion: { in: 0..5 }
  validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  # skip_before_action :verify_authenticity_token, except: [:new_ingredient]
  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
    @dose = Dose.new
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def new_ingredient
    ingredient = Ingredient.new(ingredient_params)
    ingredient.save
    # new ingredient
  end

  def destroy
    # destroy
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end

  def ingredient_params
    params.require(:ingredient).permit(:name)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def show
    # show method
  end

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render 'cocktails/new'
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @cocktail = @dose.cocktail
    @dose.destroy
    redirect_to cocktail_path(@cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :set_ingredient, only: [:show, :edit, :update, :destroy]
  def index
    @ingredients = Ingredient.all.order(:name)
  end

  def show
  end

  def new
    @ingredients = Ingredient.all.order(:name)
    @ingredient = Ingredient.new
  end

  def create
    @ingredient = Ingredient.new(ingredient_params)
    @ingredient.save
    @ingredients = Ingredient.order(:name)
    @ingredient.save
    #  redirect_to 'cocktails/ingredients/new' #ingredients_path(@ingredient)
    #else
    #  render 'cocktails/ingredients'

    #end
  end

  private

  def ingredient_params
    params.require(:ingredient).permit(:name)
  end

  def set_ingredient
    @ingredient = Ingredient.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/cocktails/index.html.erb
<%= render 'partials/navbar'  %>

<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://res.cloudinary.com/gattovi/image/upload/v1559918714/pub_e4hain.jpg);">
  <div class="container">
    <h1>Come drink where "everybody knows your name" until you forget theirs!</h1>
  </div>
</div>
<br>
<h1 style="text-align: center;">Our cocktails</h1>
<br>
<div>
  <ul class="mycontainer">
    <% @cocktails.each do |cocktail| %>
      <li class="mycardsmall">
        <div>
           <%= cl_image_tag(cocktail.photo, crop: :scale, width: 200, height: 250, crop: :fit, class:"picture" ) %><br>
          <%= link_to cocktail.name, cocktail_path(cocktail) %>
        </div>
      </li>
    <% end %>
  </ul>
</div>
<br>

app/views/cocktails/new.html.erb
<%= render 'partials/navbar'  %>

<div class="content">
  <div class="mycard">
    <div class="inside">
      <h1>New cocktail</h1>
      <%= simple_form_for(@cocktail) do |f| %>
        <%= f.input :name %>
        <%= f.input :photo %>
        <%= f.input :photo_cache, as: :hidden %>
        <%= f.button :submit, class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

<!--%= link_to "Back to Cocktails", cocktails_path %-->

app/views/cocktails/show.html.erb
<div id="getNewIngredientsModal" class="modal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">New ingredient</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form action="/new_ingredient" method="POST">
          <input id="newIngredient" name="ingredient[name]" type="text" class="form-control">
            <%= hidden_field_tag :authenticity_token, form_authenticity_token %>

          <div class="modal-footer">
            <button id="confirmNewIngredient"type="submit" class="btn btn-primary">Save changes</button>
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

<%= render 'partials/navbar'  %>
<div class="content">
  <div class="mycard">
    <%= cl_image_tag(@cocktail.photo, crop: :scale, width: 400) %>
    <br>
    <div class="inside">
      <h3><%= @cocktail.name %></h3>
      <p>Ingredients</p>
      <ul>
        <% @cocktail.doses.each do |dose| %>
        <li>
          <%= dose.ingredient.name + ' [' + dose.description + '] ' %>
          <%= link_to ('<i class="fas fa-times"></i>').html_safe, dose_path(dose) , method: :delete,
          data: { confirm: "Are you sure?" } %>

        </li>
        <% end %>
      </ul>
    </div>
  </div>

  <br><br>

  Add a new ingredient:<br>
  <div class="mycard">
    <div class="inside">
      <%= simple_form_for [@cocktail, @dose] do |f| %>
        <!--%= cl_image_tag @cocktail.photo, height: 300, width: 400, crop: :fill % -->
        <%= f.association :ingredient, as: :select %>
        <!--button id="addIngredientBtn" type="button" class="btn btn-primary">Add new ingredient</button-->
        <%= f.input :description %>
        <%= f.button :submit, class: "btn btn-info" %>
      <% end %>
    </div>
  </div>
  <br>
</div>

app/views/doses/new.html.erb
<%= simple_form_for [@cocktail, @dose] do |f| %>
  <%= f.association :ingredient %>
  <%= f.input :description %>
  <%= f.button :submit, class: "btn" %>
<% end %>

app/views/ingredients/index.html.erb
<%= render 'partials/navbar'  %>
<div class="content">
  <div class="mycard">
    <!--%= cl_image_tag(@cocktail.photo, crop: :scale, width: 400) %-->
    <br>
    <div class="inside">
      <p>Ingredients</p>
      <ul>
        <% @ingredients.each do |ingredient| %>
        <li>
          <%= ingredient.name  %>
          <!--%= link_to ('<i class="fas fa-times"></i>').html_safe, ingredient_path(ingredient) , method: :delete,
          data: { confirm: "Are you sure?" } %-->
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/ingredients/new.html.erb
<%= render 'partials/navbar'  %>
<div class="content">
  <div class="mycard">
    <!--%= cl_image_tag(@cocktail.photo, crop: :scale, width: 400) %-->
    <br>
    <div class="inside">
      <h3>Existing ingredients</h3>
      <ul>
        <% @ingredients.each do |ingredient| %>
        <li>
          <%= ingredient.name  %>
          <!--%= link_to ('<i class="fas fa-times"></i>').html_safe, dose_path(dose) , method: :delete,
          data: { confirm: "Are you sure?" } %-->
        </li>
        <% end %>
      </ul>
    </div>
  </div>
  <br>
  <div class="mycard">
    <div class="inside">
    <h3>New ingredient</h3>
    <%= simple_form_for(@ingredient) do |f| %>
      <%= f.input :name %>
      <%= f.button :submit, class: "btn btn-primary" %>
    <% end %>
    </div>
  </div>
</div>

app/views/ingredients/show.html.erb
<%= render 'partials/navbar'  %>
<div class="content">
  <div class="mycard">
    <!--%= cl_image_tag(@cocktail.photo, crop: :scale, width: 400) %-->
    <br>
    <div class="inside">
      <p>Ingredients</p>
      <ul>
        <% @ingredients.each do |ingredient| %>
        <li>
          <%= ingredient.name  %>
          <%= link_to ('<i class="fas fa-times"></i>').html_safe, dose_path(dose) , method: :delete,
          data: { confirm: "Are you sure?" } %>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <%= javascript_include_tag "application" %> <!-- from app/assets/javascripts/application.js -->
    <%= javascript_pack_tag "application" %>    <!-- from app/javascript/packs/application.js -->
  </body>
</html>

app/views/partials/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <a class="navbar-brand" href="/cocktails">
    <i class="fas fa-cocktail"></i>
    <!--img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" /-->
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <!--li class="nav-item active">
        <%= link_to "Home", cocktails_path, class: "nav-link" %>
      </li-->
      <li class="nav-item dropdown">
        <span class="dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">New</span>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="/cocktails/new">New cocktail</a>
          <a class="dropdown-item" href="/cocktails/ingredients/new">New ingredient</a>
        </div>
      </li-->
    </ul>
  </div>
</div>
<br>

app/views/partials/ingredients.html.erb
<h1 class="cocktail-color"><%= @cocktail.name %></h1>

<% @cocktail.doses.each do |d| %>
  <h2 class="ingredient-color">
    <span class="ingredient-quantity"><%= d.description %></span>
    <%= d.ingredient.name %>
    <%= link_to :delete, dose_path(d, cocktail_id: params[:id]),
        method: :delete,
        data: { confirm: 'Are you sure?' } %>
  </h2>
<% end %>